"title": "Hyperbolic Trajectory Understanding and Application"
"description": "This blueprint evaluates an LLM's comprehension of hyperbolic trajectories in astrodynamics, focusing on nuanced definitions, key parameters, and practical applications like planetary flybys and collision avoidance."
"prompts":
  - "prompt": "Describe the fundamental characteristic that distinguishes a hyperbolic trajectory from an elliptical orbit in terms of energy and eccentricity. Explain why this distinction is crucial for understanding space missions."
    "should":
      - "States that a hyperbolic trajectory has positive specific orbital energy, while an elliptical orbit has negative specific orbital energy."
      - "Mentions that the orbital eccentricity of a hyperbolic trajectory is greater than one (e > 1), whereas for an elliptical orbit, it is between zero and one (0 <= e < 1)."
      - "Explains that positive energy allows an object to escape the central body's gravitational pull, making hyperbolic trajectories essential for interplanetary travel and escape maneuvers."
      - "Connects the eccentricity difference to the open (hyperbolic) vs. closed (elliptical) nature of the orbits."
    "should_not":
      - "Confuses the energy states of hyperbolic and elliptical orbits."
      - "Incorrectly states the eccentricity ranges for either orbit type."
      - "Fails to explain the practical implications of these differences for space missions."
  - "prompt": "Explain the concept of 'hyperbolic excess velocity' and its relationship to the specific orbital energy of a hyperbolic trajectory. How does a relatively small increase in velocity near a central body lead to a significant hyperbolic excess velocity, and what is this phenomenon called?"
    "should":
      - "Defines hyperbolic excess velocity as the velocity a body attains as its distance from the central body tends to infinity."
      - "States that hyperbolic excess velocity is directly linked to the specific orbital energy (or characteristic energy C3) of the orbit."
      - "Explains that a small additional delta-v above escape speed results in a disproportionately large hyperbolic excess velocity due to the Oberth effect."
      - "Identifies the phenomenon as the Oberth effect."
    "should_not":
      - "Confuses hyperbolic excess velocity with escape velocity."
      - "Fails to mention or incorrectly describes the Oberth effect."
      - "Does not connect hyperbolic excess velocity to specific orbital energy."
  - "prompt": "In the context of a planetary flyby, what is the 'impact parameter' and how is it used to predict the outcome of an encounter, such as a potential collision? Provide an example scenario where the impact parameter is critical."
    "should":
      - "Defines the impact parameter as the distance by which a body, if it continued on an unperturbed path, would miss the central body at its closest approach."
      - "Explains that if the periapsis distance (calculated using the impact parameter and other knowns) is less than the planet's radius, an impact is expected."
      - "Provides a concrete example, such as a comet approaching Earth or Jupiter, illustrating how a minimum impact parameter is required to avoid collision."
      - "Mentions that for bodies experiencing gravitational forces and following hyperbolic trajectories, the impact parameter is equal to the semi-minor axis of the hyperbola."
    "should_not":
      - "Confuses impact parameter with periapsis distance or semi-major axis."
      - "Fails to explain its role in collision prediction."
      - "Does not provide a relevant example or provides an inaccurate one."
  - "prompt": "The semi-major axis of a hyperbolic trajectory is often described as 'not immediately visible' and is conventionally negative. Explain why it's considered negative and how it can still be 'constructed' despite its abstract nature for hyperbolic paths."
    "should":
      - "Explains that the semi-major axis is conventionally negative for hyperbolic trajectories to maintain consistency with equations used for elliptical orbits."
      - "States that it can be constructed as the distance from periapsis to the point where the two asymptotes cross."
      - "Clarifies that despite being negative, its absolute value is used in calculations like the vis-viva equation."
    "should_not":
      - "States that the semi-major axis is physically negative in space."
      - "Fails to explain the convention or its construction."
      - "Confuses its role with other orbital parameters."
  - "prompt": "Discuss how the orbital eccentricity (e) of a hyperbolic trajectory influences the shape of the hyperbola and the angle between its asymptotes. What happens to the shape as eccentricity increases significantly?"
    "should":
      - "States that for a hyperbolic trajectory, eccentricity (e) is greater than 1."
      - "Explains that eccentricity is directly related to the angle between the asymptotes."
      - "Describes that with eccentricity just over 1, the hyperbola is a sharp 'v' shape."
      - "Mentions specific examples like e=sqrt(2) resulting in right-angle asymptotes."
      - "Explains that as eccentricity increases further, the motion approaches a straight line, and the asymptotes become wider apart (e.g., e>2, asymptotes > 120 degrees apart)."
    "should_not":
      - "Confuses the relationship between eccentricity and asymptote angle."
      - "Provides incorrect examples of eccentricity values and their corresponding shapes."
      - "Fails to describe the progression of the shape as eccentricity increases."
  - "prompt": "Beyond predicting collisions, how can a spacecraft flyby utilizing a hyperbolic trajectory be used to determine the mass of a central body, even if its mass is not precisely known beforehand?"
    "should":
      - "Explains that the standard gravitational parameter (and thus mass) of the central body can be determined by measuring the deflection angle of the smaller body."
      - "States that this determination requires accurate knowledge of the impact parameter and the approach speed of the spacecraft."
      - "Highlights that because these variables can typically be determined accurately during a flyby, it provides a good estimate of the body's mass."
    "should_not":
      - "Suggests direct measurement of mass without explaining the method."
      - "Omits the critical role of deflection angle, impact parameter, or approach speed."
      - "Implies that the mass is known prior to the flyby."