name: Blueprint JSON Validation

on:
  pull_request:
    paths:
      - 'blueprints/**.json'

jobs:
  validate-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Find Blueprint JSON files
        id: find_blueprint_files
        run: |
          blueprint_files=$(find blueprints -name '*.json' -type f -print0 | xargs -0 -r echo)
          if [ -z "$blueprint_files" ]; then
            echo "No blueprint files found to validate."
            echo "blueprint_files_to_check=" >> "$GITHUB_OUTPUT"
          else
            echo "blueprint_files_to_check=$blueprint_files" >> "$GITHUB_OUTPUT"
          fi
        shell: bash

      - name: Validate Blueprint JSON files
        if: steps.find_blueprint_files.outputs.blueprint_files_to_check != ''
        run: |
          python .github/scripts/validate_blueprints.py ${{ steps.find_blueprint_files.outputs.blueprint_files_to_check }}
        shell: bash 